blog/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^blog/$', 'blog.views.post_list', name='post_list'),
    url(r'^blog/(?P<pk>\d+)/$', 'blog.views.post_detail', name='post_detail'),
    ]

co1/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse

def hello(request):
    return HttpResponse('''
        <h1>Hello, <a href="http://facebook.com/askdjango/" target="_blank">AskDjango</a></h1>
    ''')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$' , hello),
    url('', include('blog.urls', namespace="blog")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length = 100)
    content = models.TextField()
    photo = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

# Create your models here.

blog/views.py
from django.shortcuts import render
from .models import Post

def post_list(request):
    post_list = Post.objects.all()
    return render(request, 'blog/post_list.html', {'post_list' : post_list, })

def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'blog/post_detail.html', {'post' : post, })
# Create your views here.

blog/templates/blog/base.html
<!Doctype html>
<html>
<head>
<meta charste="utf-8" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
<title>Molecule</title>
<style>
body {
  padding-top:60px;
  padding-bottom:60px;
}
</style>
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
  {% block content %}
    {% endblock %}


    </div><!-- /.container -->

</body>
</html>

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}

<h1> {{ post.title }} </h1>
<img src="{{ post.photo.url }}" />
<hr/>
{{ post.content }}
<hr/>
<a href="{% url "blog:post_list" %}"> 글 목록으로 </a>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
<ul>
{% for post in post_list %}
<li>
    <a href="{% url 'blog:post_detail' post.pk %}">
    {{ post.title}}
    </a>
</li>
{% endfor %}
</ul>

{% endblock %}